### ISSUE TITLE
503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by alesrebec** [spleshka/drupal-reactjs-docker#3]
**PROBLEM:**

I was getting "503 Service Temporarily Unavailable" after following the installation steps for all URLs.

It appeared there are some issues with docker-compose version 2 configuration and nginx-proxy
https://github.com/jwilder/nginx-proxy/issues/426
https://github.com/jwilder/nginx-proxy/issues/502

**SOLUTION:**

I had to run `docker network create proxy-nginx` and restart docker containers to get it running.

**Comment by spleshka** [comment]
Thanks Ales!

What's your OS / Docker versions? 
It certainly worth mentioning o=nn the documentation, I'd just like to get more clarity if it's OS-specifig thing or a global bug.

**Comment by alesrebec** [comment]
I'm running Ubuntu 16.04 LTS with Linux kernel 4.4.0-67
Docker version: Docker version 17.03.0-ce, build 3a232c8

Created a pull request here: https://github.com/spleshka/drupal-reactjs-docker/pull/8

**Comment by spleshka** [comment]
That's interesting, I was testing on Ubuntu as well with no issues. However, I assume other devs might meet similar issue to yours, so having additional note in the readme is always a good idea. Merged PR.

Thanks Ales!

**Comment by BrajeshOfficial** [comment]
I have also the same issue can someone help

**Comment by spleshka** [comment]
Hi @BrajeshOfficial, this repo is officially abandoned - please, use its successor https://github.com/systemseed/drupal_reactjs_boilerplate
