### ISSUE TITLE
Use traefik as reverse proxy

### ISSUE THREAD

**Issue by alesrebec** [spleshka/drupal-reactjs-docker#4]
docker4drupal 2.x is now using traefik as reverse proxy.

http://docs.docker4drupal.org/en/latest/domains/
It keeps our /etc/hosts file clean too.

**Comment by spleshka** [comment]
Hi Ales,

I don't really mind to get nginxproxy replaced by traefik. I'll update docker compose file to the latest docker4drupal config when I get some time. Hopefully till the end of this week. However, if you're willing to contribute - you're very welcome!

**Comment by spleshka** [comment]
Thanks @alesrebec for raising this issue, I've reconfigured docker-compose.yml and updated docs to use traefik and the latest containers from docker4drupal.
