### ISSUE TITLE
CLI to run Drush from outside the backend_php container

### ISSUE THREAD

**Issue by alesrebec** [spleshka/drupal-reactjs-docker#7]
According to `Note that Drush and Drupal Console have to be invoked inside of web folder, so you'll have to cd web first.`
We can fix that and have a direct command like `docker-compose run backend_php drush dis devel` to execute drush command from outside backend_php container.
I docker4drupal this is taken care of.

**Comment by alesrebec** [comment]
You can call drush with --root parameter to specify the Drupal dir is in "./web/" folder.

`docker-compose run backend_php drush --root="./web/" <COMMAND>` 

Example:
`docker-compose run backend_php drush --root="./web/" status` for drush status

**Comment by spleshka** [comment]
This is a very good point. I was thinking about direction developers inside of the container to avoid long commands (remember - keep it simple!). However, I think it's a good idea to add both options to the documentation and then let devs decide which option works for them.

**Comment by alesrebec** [comment]
I have all (long) docker commands in my user's bash aliases file.

To make your lives easier just add this to yours:

`alias dcdocker=docker-compose run backend_php drush --root="./web/"`

and then just run dcdocker from your folder where docker-composer.yml resides and you are executing commands in your backend_php container.

**Comment by spleshka** [comment]
Thanks @alesrebec, added notes to the documentation!
